services:
  #MongoDB
  mongo_db:
    container_name: vocab_mongo_db
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  back:
    build: ./back
    ports:
      - 8080:8080
    working_dir: /app/back
    volumes:
      - ./back:/app/back
      - /app/back/node_modules
    depends_on:
      - mongo_db
    environment:
      MONGO_URL: mongodb://mongo_db:27017/sora
      PORT: 8080
    entrypoint: ['yarn', 'dev']

  front:
    build: ./web
    ports:
      - 3000:3000
    working_dir: /app/web
    volumes:
      - ./web:/app/web
      - /app/web/node_modules
    entrypoint: ['yarn', 'dev']

volumes:
  mongo_db: {}
