// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPcqhBq1HWy_0NFWGnV4mVRrlyC19DvtM',
    appId: '1:946696955351:android:02aec3a671b6e5d38d9792',
    messagingSenderId: '946696955351',
    projectId: 'enhance-vocab',
    storageBucket: 'enhance-vocab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKq9FaYL6M9rLplcul_9ycn-hUes7wirU',
    appId: '1:946696955351:ios:282671a5e03c52378d9792',
    messagingSenderId: '946696955351',
    projectId: 'enhance-vocab',
    storageBucket: 'enhance-vocab.appspot.com',
    androidClientId: '946696955351-7v61tuiak51bb59mtq93f9ovfv7cf9an.apps.googleusercontent.com',
    iosClientId: '946696955351-3requ20ao13oudpkkgi6djdl9ooa84c7.apps.googleusercontent.com',
    iosBundleId: 'mn.endurdbn.vocab',
  );

}